function getCountries() {
  return [
    'Caribbean Netherlands',
    'China',
    'Heard Island and McDonald Islands',
    'Cyprus',
    'Guinea-Bissau',
    'São Tomé and Príncipe',
    'Laos',
    'Albania',
    'Sudan',
    'Oman',
    'Vatican City',
    'Nigeria',
    'Egypt',
    'Chile',
    'Ivory Coast',
    'Cape Verde',
    'Japan',
    'United States Minor Outlying Islands',
    'Spain',
    'Central African Republic',
    'Djibouti',
    'Denmark',
    'Russia',
    'Timor-Leste',
    'Sint Maarten',
    'New Zealand',
    'Togo',
    'Antarctica',
    'Malawi',
    'Azerbaijan',
    'Barbados',
    'Kosovo',
    'Mongolia',
    'Saint Helena, Ascension and Tristan da Cunha',
    'French Guiana',
    'Gabon',
    'Austria',
    'Saudi Arabia',
    'Samoa',
    'Bhutan',
    'Republic of the Congo',
    'Fiji',
    'Paraguay',
    'Åland Islands',
    'Suriname',
    'Turks and Caicos Islands',
    'Chad',
    'San Marino',
    'Macau',
    'Australia',
    'Eritrea',
    'Guernsey',
    'Micronesia',
    'Venezuela',
    'Saint Pierre and Miquelon',
    'Sierra Leone',
    'Ecuador',
    'Senegal',
    'Libya',
    'Indonesia',
    'Bangladesh',
    'Svalbard and Jan Mayen',
    'Tanzania',
    'Madagascar',
    'Cook Islands',
    'Sweden',
    'Honduras',
    'Panama',
    'Aruba',
    'North Macedonia',
    'Angola',
    'Jersey',
    'Dominica',
    'Palestine',
    'Uzbekistan',
    'Falkland Islands',
    'Malta',
    'Lebanon',
    'South Georgia',
    'Georgia',
    'Italy',
    'Maldives',
    'Northern Mariana Islands',
    'Kyrgyzstan',
    'Marshall Islands',
    'Peru',
    'United Arab Emirates',
    'Pitcairn Islands',
    'Norway',
    'Nauru',
    'Uganda',
    'Uruguay',
    'Croatia',
    'Kuwait',
    'Papua New Guinea',
    'Ireland',
    'Armenia',
    'Greenland',
    'United States Virgin Islands',
    'Guam',
    'Israel',
    'Brunei',
    'Hungary',
    'Isle of Man',
    'Ukraine',
    'Botswana',
    'Belgium',
    'Tonga',
    'Benin',
    'Antigua and Barbuda',
    'Thailand',
    'Cuba',
    'Zambia',
    'Christmas Island',
    'Kenya',
    'Eswatini',
    'New Caledonia',
    'South Sudan',
    'Poland',
    'American Samoa',
    'Mali',
    'Nicaragua',
    'Tokelau',
    'Guatemala',
    'Jordan',
    'Bolivia',
    'Norfolk Island',
    'Ghana',
    'Andorra',
    'Mozambique',
    'Dominican Republic',
    'British Indian Ocean Territory',
    'Gibraltar',
    'Qatar',
    'Philippines',
    'Slovakia',
    'Argentina',
    'South Africa',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Rwanda',
    'Martinique',
    'Kazakhstan',
    'Greece',
    'Malaysia',
    'Lesotho',
    'Faroe Islands',
    'Netherlands',
    'Canada',
    'India',
    'Syria',
    'Iceland',
    'Monaco',
    'Iraq',
    'Morocco',
    'Curaçao',
    'Finland',
    'Bahamas',
    'Slovenia',
    'Bulgaria',
    'Jamaica',
    'Bahrain',
    'France',
    'Comoros',
    'Brazil',
    'Ethiopia',
    'Liechtenstein',
    'Gambia',
    'Niger',
    'Estonia',
    'Vietnam',
    'Bermuda',
    'Montenegro',
    'Cayman Islands',
    'North Korea',
    'Luxembourg',
    'Turkmenistan',
    'Palau',
    'Tunisia',
    'Western Sahara',
    'Latvia',
    'Cameroon',
    'Saint Martin',
    'French Southern and Antarctic Lands',
    'Iran',
    'Mauritania',
    'United States',
    'Mauritius',
    'British Virgin Islands',
    'Saint Barthélemy',
    'United Kingdom',
    'Montserrat',
    'Trinidad and Tobago',
    'South Korea',
    'El Salvador',
    'Taiwan',
    'Réunion',
    'Seychelles',
    'Serbia',
    'Afghanistan',
    'Colombia',
    'Pakistan',
    'Lithuania',
    'Hong Kong',
    'DR Congo',
    'Tuvalu',
    'Zimbabwe',
    'Burkina Faso',
    'Bosnia and Herzegovina',
    'Guadeloupe',
    'Singapore',
    'Equatorial Guinea',
    'Anguilla',
    'Tajikistan',
    'Cocos (Keeling) Islands',
    'Niue',
    'Germany',
    'Moldova',
    'Somalia',
    'Myanmar',
    'Czechia',
    'Romania',
    'Turkey',
    'Belarus',
    'Mayotte',
    'Nepal',
    'Bouvet Island',
    'Guyana',
    'Cambodia',
    'Grenada',
    'Mexico',
    'Burundi',
    'French Polynesia',
    'Sri Lanka',
    'Namibia',
    'Saint Vincent and the Grenadines',
    'Yemen',
    'Guinea',
    'Switzerland',
    'Kiribati',
    'Costa Rica',
    'Haiti',
    'Vanuatu',
    'Solomon Islands',
    'Wallis and Futuna',
    'Belize',
    'Puerto Rico',
    'Algeria',
    'Liberia',
    'Portugal',
  ]
}

export const countriesService = {
  getCountries,
}
